### ISSUE TITLE
Doesn't do anything

### ISSUE THREAD

**Issue by languitar** [sebastianmarkow/deoplete-rust#2]
I tried to use this deoplete source but I am unable to get this working. I installed race, cloned the rust source code, configure everything as explained. Before correct configuration, there was a startup warning that racer wasn't found. So at least some code seems to be evaluated. However, I do not get any completions. Any idea how to debug this?

**Comment by sebastianmarkow** [comment]
~~~
 let g:deoplete#sources#rust#racer_binary='path/to/racer'
~~~
Did you use the correct path to the racer binary? Are you in *nix or win?

**Comment by languitar** [comment]
Yes, without the correct path I saw a warning.

I am on OSX.

**Comment by sebastianmarkow** [comment]
The warning only pops up if the filepath set on `g:deoplete#sources#rust#racer_binary` is not a file or not executable. Check `ls -l path/to/racer` if its executable, otherwise do so via `chmod`. Also check if you can execute racer via its full path.

**Comment by languitar** [comment]
```
g:deoplete#sources#rust#racer_binary  /Users/languitar/.cargo/bin/racer

languitar@miles ~/code/rust (master)> /Users/languitar/.cargo/bin/racer
RUST_SRC_PATH environment variable must be set to point to the src directory of a rust checkout. E.g. "/home/foouser/src/rust/src"
```

Shouldn't that be enough?

**Comment by languitar** [comment]
Ok, I found the issue. The rust src variable didn't end with `src`. Maybe a warning that racer doesn't start properly would be nice.

**Comment by sebastianmarkow** [comment]
Added checks whenever racer returns an error.
Also deoplete-rust now checks if `$RUST_SRC_PATH` and `g:deoplete#sources#rust#rust_source_path` do not only exist but are none empty.

Thanks for reporting @languitar

**Comment by languitar** [comment]
Thanks!
