### ISSUE TITLE
Display parameters when calling a function

### ISSUE THREAD

**Issue by torkleyy** [sebastianmarkow/deoplete-rust#3]
It would be helpful to have the name and type of the parameters displayed when opening the `(`.

Example:

```rust
fn foo(a: u32, b: &str, c: bool) {}

fn main() { 
    foo(<caret>
       >  foo(*a: u32*, b: &str, c: bool)

    // After a
    foo(31, <caret>
          > foo(a: u32, *b: &str*, c: bool)
}
```

Note: The lines starting with `>` are the "completion popup". The parameter surrounded with `*` should be bold.

Unfortunately, I'm not using `deoplete` anymore because Rust support for vim/neovim isn't very good.

**Comment by sebastianmarkow** [comment]
Can you elaborate a bit and give a short example what functionality you need to be implemented?

**Comment by torkleyy** [comment]
@sebastianmarkow I've created a description

**Comment by ustulation** [comment]
Is this going to be implemented (or is it already done) ? There is no information on why the issue has been closed.

**Comment by sebastianmarkow** [comment]
@ustulation you may want to watch this ticket Shougo/deoplete.nvim#490 

I'm not sure if it's currently possible in deoplete. But in the meantime you can have a look at [roxma/nvim-completion-manager](https://github.com/roxma/nvim-completion-manager) and [roxma/nvim-cm-racer](https://github.com/roxma/nvim-cm-racer).
