### ISSUE TITLE
Support for showing uses of a definition?

### ISSUE THREAD

**Issue by vext01** [sebastianmarkow/deoplete-rust#5]
Hi,

A nice feature would be to show the uses of a definition.

E.g. if the cursor is on a function definition, a keybinding shows all the call sites.

Similarly for variable names etc.

Thanks

**Comment by sebastianmarkow** [comment]
Something like [qstrahl/vim-matchmaker](https://github.com/qstrahl/vim-matchmaker)?

**Comment by vext01** [comment]
It's not really the same. That looks textual, whereas I would like semantic.

**Comment by sebastianmarkow** [comment]
IMHO [phildawes/racer](https://github.com/phildawes/racer) is the better place to ask for none trivial features. Finding variables requires knowledge of the scope level, hence parsing etc pp. deoplete-rust provides merely a wrapper to racer.
